name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: retypeapp/action-build@latest
        with:
          key: ${{ secrets.RETYPE_KEY }}

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
